services:
  postgres:
    image: postgres:16-alpine
    container_name: chat_weave_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: chat_weave
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
    ports:
      - "6450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
